site_name: OCRG
site_url: https://ocrg.github.io/
site_description: Advancing cybersecurity through innovative research in threat detection and security techniques.
site_author: OCRG Team
repo_url: https://github.com/OCRG/ocrg.github.io

# Add 404 page configuration
# Note: We use .html extensions in source files and use_directory_urls: false
# to ensure consistent URL structure in production. This diverges from MkDocs'
# default behavior but is necessary for our deployment setup.
use_directory_urls: false

theme:
  name: material
  palette:
    # Terminal-style dark theme
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  logo: assets/images/ocrg-icon-040.png
  favicon: assets/images/ocrg-icon-040.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides

extra:
  analytics:
    provider: google
    property: GTM-5SD7PB52
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OCRG
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6SDUxJzSdr
    - icon: fontawesome/regular/envelope
      link: mailto:ocrg@brad-jackson.com

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - About: about.md
  - Research:
    - Overview: research/index.md
    - Steganalysis: research/steganalysis.md
    - Threat Detection: research/threat-detection.md
  - Projects: projects/index.md
  - Documentation:
    - Getting Started: documentation/getting-started.md
    - Dev Best Practices: documentation/dev-best-practices.md
    - Contributing: documentation/contributing.md
  - Contact: contact.md
  - Donate: donate.md
  - 404: 404.md

plugins:
  - search
  - social

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/banner.css
