site_name: Ozark Cybersecurity Research Group
site_url: https://ocrg.github.io/
site_description: Advancing cybersecurity through innovative research in threat detection and security techniques.
site_author: OCRG Team
repo_url: https://github.com/OCRG/ocrg.github.io

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
  logo: assets/images/orcg-icon-revised.png
  favicon: assets/images/orcg-icon-revised.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OCRG
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6SDUxJzSdr
    - icon: fontawesome/regular/envelope
      link: mailto:ocrg@brad-jackson.com

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - About: about.md
  - Research:
    - Overview: research/index.md
    - Steganalysis: research/steganalysis.md
    - Threat Detection: research/threat-detection.md
  - Documentation:
    - Getting Started: documentation/getting-started.md
    - Dev Best Practices: documentation/dev-best-practices.md
    - Contributing: documentation/contributing.md
  - Contact: contact.md

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css
