name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build site
        run: |
          mkdocs build
          
      - name: Create .nojekyll file
        run: |
          touch site/.nojekyll
          
      - name: Verify index.html exists
        run: |
          if [ ! -f site/index.html ]; then
            echo "index.html not found, creating minimal fallback file"
            echo '<html><head><meta http-equiv="refresh" content="0;URL=./home/index.html"></head><body><p>Redirecting...</p></body></html>' > site/index.html
          fi
          ls -la site/
          cat site/index.html | head -10
          
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
          clean: true # Automatically remove deleted files from the deployment
          clean-exclude: |
            .nojekyll 