name: Test MkDocs Site

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Explicitly ensure test dependencies are installed
          pip install pytest pytest-cov requests pyyaml
      
      - name: Run tests
        run: |
          python -m pytest --cov=tests
      
      - name: Build MkDocs site
        run: |
          mkdocs build
      
      - name: Test internal links
        run: |
          python tests/check_links.py docs
      
      - name: Test external links
        run: |
          python tests/check_links.py docs
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests 